[package]
name = "AdventOfCode2024"
version = "0.1.0"
authors = ["Nathan Dunne"]
edition = "2021"

[dependencies]
anyhow = "1.0.94"
regex = "1.11.1"
matches = "0.1"
strum = "0.27"
strum_macros = "0.27"
itertools = "0.14"